//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpheliaSuiteV2.Core.DataAccess.MicroSQL.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpheliaSuiteV2.Core.DataAccess.MicroSQL.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El parámetro ({0}) no tiene un valor válido.
        /// </summary>
        internal static string ArgumentException {
            get {
                return ResourceManager.GetString("ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Está intentando agregar una entidad ({0}) que ya existe en el contexto de datos.
        /// </summary>
        internal static string EntityAlreadyExistsException {
            get {
                return ResourceManager.GetString("EntityAlreadyExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad foránea ({0}) no existe en la entidad ({1}).
        /// </summary>
        internal static string ForeignPropertyDontExistsException {
            get {
                return ResourceManager.GetString("ForeignPropertyDontExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de contexto ({0}) no es válido.
        /// </summary>
        internal static string InvalidDbContextTypeException {
            get {
                return ResourceManager.GetString("InvalidDbContextTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La entidad ({0}) tiene una cantidad inválida de propiedades marcadas como llave principal.
        /// </summary>
        internal static string InvalidEntityKeyException {
            get {
                return ResourceManager.GetString("InvalidEntityKeyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de la propiedad de foránea ({0}) no es corresponde con el de la propiedad local.
        /// </summary>
        internal static string InvalidForeignPropertyException {
            get {
                return ResourceManager.GetString("InvalidForeignPropertyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación de inclusión inválida. El nivel de inclusión que intenta usar no está permitido.
        /// </summary>
        internal static string InvalidIncludeOperationException {
            get {
                return ResourceManager.GetString("InvalidIncludeOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de la propiedad de navegación ({0}) no es válido.
        /// </summary>
        internal static string InvalidNavigationPropertyException {
            get {
                return ResourceManager.GetString("InvalidNavigationPropertyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Un parámetro nulo debe ser de tipo Nullable&lt;T&gt;.
        /// </summary>
        internal static string InvalidNullableParameterException {
            get {
                return ResourceManager.GetString("InvalidNullableParameterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La operación que intenta realizar no es válida sobre la entidad ({0}).
        /// </summary>
        internal static string InvalidOperationEntityEntryException {
            get {
                return ResourceManager.GetString("InvalidOperationEntityEntryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expresión de propiedad inválida.
        /// </summary>
        internal static string InvalidPropertyExpressionException {
            get {
                return ResourceManager.GetString("InvalidPropertyExpressionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de dato de la propiedad llave en la entidad ({0}) no se ajusta con el tipo de llave.
        /// </summary>
        internal static string InvalidTypeEntityKeyException {
            get {
                return ResourceManager.GetString("InvalidTypeEntityKeyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad de navegación ({0}) no existe en la entidad ({1}).
        /// </summary>
        internal static string NavigationPropertyDontExistsException {
            get {
                return ResourceManager.GetString("NavigationPropertyDontExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El repositorio {0} no ha sido inicializado.
        /// </summary>
        internal static string NotInitializedRepositoryException {
            get {
                return ResourceManager.GetString("NotInitializedRepositoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El parámetro ({0}) no ha sido definido.
        /// </summary>
        internal static string UndefinedParameterException {
            get {
                return ResourceManager.GetString("UndefinedParameterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expresión no soportada ({0}).
        /// </summary>
        internal static string UnsupportedExpressionException {
            get {
                return ResourceManager.GetString("UnsupportedExpressionException", resourceCulture);
            }
        }
    }
}
